<?php if ($this->userLogged): ?>
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->basePath ?>">Kuestions</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="<?php echo $this->topItemAtual == 'painel' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Painel <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/main/index">Principal</a></li>
                            <li><a href="/categorias/nova-categoria">Nova Categoria</a></li>
                        </ul>
                    </li>
                    <li class="<?php echo $this->topItemAtual == 'relatorios' ? 'active' : '' ?> dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Relatórios <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="/relatorio-perguntas/todas-perguntas">Todas as Perguntas</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="#"><button class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-star"></span> Nova Pergunta</button></a></li>
                </ul>
            </div>
        </div>
    </div>
<?php endif; ?>