<div class="panel panel-default">
    <div class="panel-heading">Nova Pergunta</div>
    <div class="panel-body">
        <form role="form" class="form-horizontal" action="/perguntas/salvar-pergunta" method="post">

            <div class="form-group">
                <label class="control-label col-sm-2" for="categoria">Categoria</label>
                <div class="col-sm-4">
                    <select name="categoria" class="form-control" required>
                        <option value="">Selecione</option>
                        <?php foreach ($this->categorias as $categoria): ?>
                            <option value="<?php echo $categoria['cod'] ?>"><?php echo $categoria['nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="descricao">Pergunta</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="descricao" placeholder="Pergunta" required />
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-sm-2" for="descricao">Alternativas</label>
                <div class="col-sm-4">
                    <ul class="nav nav-pills nav-stacked">
                        <?php for ($i = 1; $i <= 5; $i++): ?>
                            <li class="bg-info img-rounded">
                                <a>
                                    <div class="input-group">
                                        <span class="input-group-addon">
                                            <input type="radio" name="correta" value="<?php echo $i ?>" />
                                        </span>
                                        <input type="text" name="alternativa<?php echo $i ?>" class="form-control col-sm-5" placeholder="Alternativa <?php echo $i ?>" required />
                                    </div>
                                </a>
                            </li>
                        <?php endfor; ?>
                    </ul>
                </div>
            </div>
            
            <div class="form-group">
                <label class="control-label col-sm-2" for="tags">Tags</label>
                <div class="col-sm-4">
                    <input type="text" class="form-control" name="tags" placeholder="Tags separadas por vírgulas" required />
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                </div>
            </div>

        </form>
    </div>
</div>