<form role="form" class="form-horizontal well" action="/categorias/salvar-categoria" method="post">
    <h4>Nova Categoria</h4>
    <hr />
    <div class="form-group">
        <label class="control-label col-sm-2" for="pai">Pai</label>
        <div class="col-sm-4">
            <select name="pai" class="form-control">
                <option value="0">Nenhum</option>
                <?php foreach($this->categorias as $categoria): ?>
                    <option value="<?php echo $categoria['cod'] ?>"><?php echo $categoria['nome'] ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="form-group">
        <label class="control-label col-sm-2" for="nome">Nome</label>
        <div class="col-sm-4">
            <input type="text" class="form-control" name="nome" placeholder="Nome da Categoria" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-4">
            <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
    </div>
</form>