<div class="input-group hidden" id="categoria-template">
    <select class="form-control">
        <option value="">Selecione</option>
        <?php foreach ($this->categorias as $categoria): ?>
            <option value="<?php echo $categoria['cod'] ?>"><?php echo $categoria['nome'] ?></option>
        <?php endforeach; ?>
    </select>
    <div class="input-group-btn">
        <button class="btn btn-success btn-save-categoria"><span class="glyphicon glyphicon-save"></span></button>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">Todas as Perguntas</div>
    <div class="panel-body">
        <form class="form-horizontal" role="form">
            <div class="form-group">
                <label for="categoria" class="col-sm-2 control-label">Categoria</label>
                <div class="col-sm-4">
                    <select id="categoria" name="categoria" class="form-control">
                        <option value="">Selecione</option>
                        <?php foreach ($this->categorias as $categoria): ?>
                            <option value="<?php echo $categoria['cod'] ?>"><?php echo $categoria['nome'] ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label for="descricao" class="col-sm-2 control-label">Descrição</label>
                <div class="col-sm-4">
                    <input type="text" name="descricao" id="descricao" class="form-control" placeholder="Descrição da Pergunta" />
                </div>
            </div>
            <div class="form-group">
                <label for="status" class="col-sm-2 control-label">Status</label>
                <div class="col-sm-4">
                    <select name="status" id="status" class="form-control">
                        <option value="">Selecione</option>
                        <option value="1">Ativo</option>
                        <option value="2">Inativo</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-primary">Pesquisar</button>
                </div>
            </div>
        </form>
    </div>
    <?php if (count($this->listagem)): ?>
        <table class="table table-bordered table-condensed table-hover table-responsive table-striped">
            <thead>
                <tr>
                    <th>Categoria</th>
                    <th>Pergunta</th>
                    <th>Alternativas</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($this->listagem as $row): ?>
                    <tr>
                        <td class="categoria-edit text-center" data-cod="<?php echo $row['cod'] ?>" data-categoria="<?php echo $row['categoria'] ?>" data-edit="hidden"><?php echo $row['categoria_desc'] ?></td>
                        <td class="descricao-edit" data-cod="<?php echo $row['cod'] ?>" data-edit="hidden"><?php echo $row['descricao'] ?></td>
                        <td>
                            <ul class="nav nav-pills nav-stacked">
                                <li>
                                    <a class="alternativa-edit <?php echo $row['alternativa1'] == $row['correta'] ? 'bg-success' : '' ?>" data-cod="<?php echo $row['alternativa1'] ?>" data-edit="hidden"><?php echo $row['alternativa1_desc'] ?></a>
                                </li>
                                <li>
                                    <a class="alternativa-edit <?php echo $row['alternativa2'] == $row['correta'] ? 'bg-success' : '' ?>" data-cod="<?php echo $row['alternativa2'] ?>" data-edit="hidden"><?php echo $row['alternativa2_desc'] ?></a>
                                </li>
                                <li>
                                    <a class="alternativa-edit <?php echo $row['alternativa3'] == $row['correta'] ? 'bg-success' : '' ?>" data-cod="<?php echo $row['alternativa3'] ?>" data-edit="hidden"><?php echo $row['alternativa3_desc'] ?></a>
                                </li>
                                <li>
                                    <a class="alternativa-edit <?php echo $row['alternativa4'] == $row['correta'] ? 'bg-success' : '' ?>" data-cod="<?php echo $row['alternativa4'] ?>" data-edit="hidden"><?php echo $row['alternativa4_desc'] ?></a>
                                </li>
                                <li>
                                    <a class="alternativa-edit <?php echo $row['alternativa5'] == $row['correta'] ? 'bg-success' : '' ?>" data-cod="<?php echo $row['alternativa5'] ?>" data-edit="hidden"><?php echo $row['alternativa5_desc'] ?></a>
                                </li>
                            </ul>
                        </td>
                        <td>
                            <button class="btn-change-status btn btn-<?php echo $row['status'] == 2 ? 'success' : 'danger' ?>" data-cod="<?php echo $row['cod'] ?>" data-status="<?php echo $row['status'] ?>">
                                <span class="glyphicon glyphicon-thumbs-<?php echo $row['status'] == 2 ? 'up' : 'down' ?>"></span>
                            </button>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
            <tfoot>
                <tr class="text-center">
                    <td colspan="4">
                        <ul class="pagination">
                            <li class="disabled"><a href="#">&laquo;</a></li>
                            <li class="active"><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">&raquo;</a></li>
                        </ul>

                    </td>
                </tr>
            </tfoot>
        </table>
    <?php endif; ?>
</div>